# Generated by Django 5.1 on 2024-08-22 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_postimages_alter_post_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="postimages",
            name="post",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="main.post"
            ),
            preserve_default=False,
        ),
    ]
