# Generated by Django 5.1 on 2024-08-22 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_postimages_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="picture",
        ),
        migrations.AddField(
            model_name="post",
            name="pictures",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="main.postimages"
            ),
        ),
        migrations.AlterField(
            model_name="postimages",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="main.post",
            ),
        ),
    ]
