# Generated by Django 5.1 on 2024-08-22 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_post_picture_post_pictures_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="pictures",
        ),
        migrations.AlterField(
            model_name="postimages",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pictures",
                to="main.post",
            ),
        ),
    ]
