# Generated by Django 5.1 on 2024-08-22 07:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_reply_alter_comment_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="date_comment",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="reply",
            name="date_reply",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
