# Generated by Django 5.1 on 2024-08-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_comment_date_comment_reply_date_reply"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
    ]
